# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 23:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='created_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
