# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 23:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171226_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_Date',
            new_name='created_date',
        ),
    ]
